public class ExecuteAsi {
    public void check(String a, String b, String c, String d, String e, String f, String g, String h) {
        System.debug('Hello');
    }
     public void check1(String a, String b, String c, String d, String e, String f, String g, String h) {
        System.debug('Hellov22.26');
    }
    public void check3(String a, String b, String c, String d, String e, String f, String g, String h) {
        System.debug('Hellov22.26');
    }
}