public class ExecuteLogic {
    public void check(String a, String b, String c, String d, String e, String f, String g, String h, String i) {
        System.debug('Hello');
        System.debug('Hello');
        System.debug('Hello');
    }
    public void check1(String a, String b, String c, String d, String e, String f, String g, String h, String i) {
        System.debug('Hello');
        System.debug('Hello2');
    }
    public void check2(String a, String b, String c, String d, String e, String f, String g, String h, String i) {
        System.debug('Hello');
    }
}