public class Execute144PMD {
    public class LogicParams {
        String a;
        String b;
        String c;
        String d;
        String e;
        String f;
        String g;
        String h;
        String i;
    }

    public void check(LogicParams params) {
        System.debug('Hola');
        System.debug('Hola');
        System.debug('Hola FridaySat');
        // Use params.a, params.b, etc., instead of individual parameters
    }
}