public class GovCloud {
    public String check(String a, String b, String c, String d, String e, String f, String g, String h) {
        if (string.isBlank(a)) {
            return a;
        } else if (string.isBlank(b)) {
            return b;
        } else {
            return c;
        }
        
    }
     public void check1(String a, String b, String c, String d, String e, String f, String g, String h) {
        System.debug('Hellov22.26');
    }
    public void check3(String a, String b, String c, String d, String e, String f, String g, String h) {
        System.debug('Hellov22.26');
       //June 2024 EMEA Test
    }
    public void check4(String a, String b, String c, String d, String e, String f, String g, String h) {
        System.debug('Hellov22.26');
       //June 2024 EMEA Test
    }
    public void check5(String a, String b, String c, String d, String e, String f, String g, String h) {
        System.debug('Hellov22.26');
       //July 2024 EMEA Test
    }
}